// Generated by tools/gen_d3d9_stubs.py from the Windows SDK's d3d9.h; do not edit.
#pragma once

#include <d3d9.h>

namespace cw::d3d {

// Logs the first call of each unimplemented method; returns E_NOTIMPL.
HRESULT stubCalled(const char* method);

struct StubDirect3DDevice9 : IDirect3DDevice9 {
    LONG m_refs = 1;
    virtual ~StubDirect3DDevice9() = default;
    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, void** ppvObj) override { if (ppvObj) *ppvObj = nullptr; return E_NOINTERFACE; }
    ULONG STDMETHODCALLTYPE AddRef() override { return static_cast<ULONG>(InterlockedIncrement(&m_refs)); }
    ULONG STDMETHODCALLTYPE Release() override { const LONG refs = InterlockedDecrement(&m_refs); if (refs == 0) delete this; return static_cast<ULONG>(refs); }
    HRESULT STDMETHODCALLTYPE TestCooperativeLevel() override { return stubCalled("TestCooperativeLevel"); }
    UINT STDMETHODCALLTYPE GetAvailableTextureMem() override { stubCalled("GetAvailableTextureMem"); return {}; }
    HRESULT STDMETHODCALLTYPE EvictManagedResources() override { return stubCalled("EvictManagedResources"); }
    HRESULT STDMETHODCALLTYPE GetDirect3D(IDirect3D9** ppD3D9) override { return stubCalled("GetDirect3D"); }
    HRESULT STDMETHODCALLTYPE GetDeviceCaps(D3DCAPS9* pCaps) override { return stubCalled("GetDeviceCaps"); }
    HRESULT STDMETHODCALLTYPE GetDisplayMode(UINT iSwapChain,D3DDISPLAYMODE* pMode) override { return stubCalled("GetDisplayMode"); }
    HRESULT STDMETHODCALLTYPE GetCreationParameters(D3DDEVICE_CREATION_PARAMETERS *pParameters) override { return stubCalled("GetCreationParameters"); }
    HRESULT STDMETHODCALLTYPE SetCursorProperties(UINT XHotSpot,UINT YHotSpot,IDirect3DSurface9* pCursorBitmap) override { return stubCalled("SetCursorProperties"); }
    void STDMETHODCALLTYPE SetCursorPosition(int X,int Y,DWORD Flags) override { stubCalled("SetCursorPosition"); }
    BOOL STDMETHODCALLTYPE ShowCursor(BOOL bShow) override { stubCalled("ShowCursor"); return {}; }
    HRESULT STDMETHODCALLTYPE CreateAdditionalSwapChain(D3DPRESENT_PARAMETERS* pPresentationParameters,IDirect3DSwapChain9** pSwapChain) override { return stubCalled("CreateAdditionalSwapChain"); }
    HRESULT STDMETHODCALLTYPE GetSwapChain(UINT iSwapChain,IDirect3DSwapChain9** pSwapChain) override { return stubCalled("GetSwapChain"); }
    UINT STDMETHODCALLTYPE GetNumberOfSwapChains() override { stubCalled("GetNumberOfSwapChains"); return {}; }
    HRESULT STDMETHODCALLTYPE Reset(D3DPRESENT_PARAMETERS* pPresentationParameters) override { return stubCalled("Reset"); }
    HRESULT STDMETHODCALLTYPE Present(const RECT* pSourceRect,const RECT* pDestRect,HWND hDestWindowOverride,const RGNDATA* pDirtyRegion) override { return stubCalled("Present"); }
    HRESULT STDMETHODCALLTYPE GetBackBuffer(UINT iSwapChain,UINT iBackBuffer,D3DBACKBUFFER_TYPE Type,IDirect3DSurface9** ppBackBuffer) override { return stubCalled("GetBackBuffer"); }
    HRESULT STDMETHODCALLTYPE GetRasterStatus(UINT iSwapChain,D3DRASTER_STATUS* pRasterStatus) override { return stubCalled("GetRasterStatus"); }
    HRESULT STDMETHODCALLTYPE SetDialogBoxMode(BOOL bEnableDialogs) override { return stubCalled("SetDialogBoxMode"); }
    void STDMETHODCALLTYPE SetGammaRamp(UINT iSwapChain,DWORD Flags,const D3DGAMMARAMP* pRamp) override { stubCalled("SetGammaRamp"); }
    void STDMETHODCALLTYPE GetGammaRamp(UINT iSwapChain,D3DGAMMARAMP* pRamp) override { stubCalled("GetGammaRamp"); }
    HRESULT STDMETHODCALLTYPE CreateTexture(UINT Width,UINT Height,UINT Levels,DWORD Usage,D3DFORMAT Format,D3DPOOL Pool,IDirect3DTexture9** ppTexture,HANDLE* pSharedHandle) override { return stubCalled("CreateTexture"); }
    HRESULT STDMETHODCALLTYPE CreateVolumeTexture(UINT Width,UINT Height,UINT Depth,UINT Levels,DWORD Usage,D3DFORMAT Format,D3DPOOL Pool,IDirect3DVolumeTexture9** ppVolumeTexture,HANDLE* pSharedHandle) override { return stubCalled("CreateVolumeTexture"); }
    HRESULT STDMETHODCALLTYPE CreateCubeTexture(UINT EdgeLength,UINT Levels,DWORD Usage,D3DFORMAT Format,D3DPOOL Pool,IDirect3DCubeTexture9** ppCubeTexture,HANDLE* pSharedHandle) override { return stubCalled("CreateCubeTexture"); }
    HRESULT STDMETHODCALLTYPE CreateVertexBuffer(UINT Length,DWORD Usage,DWORD FVF,D3DPOOL Pool,IDirect3DVertexBuffer9** ppVertexBuffer,HANDLE* pSharedHandle) override { return stubCalled("CreateVertexBuffer"); }
    HRESULT STDMETHODCALLTYPE CreateIndexBuffer(UINT Length,DWORD Usage,D3DFORMAT Format,D3DPOOL Pool,IDirect3DIndexBuffer9** ppIndexBuffer,HANDLE* pSharedHandle) override { return stubCalled("CreateIndexBuffer"); }
    HRESULT STDMETHODCALLTYPE CreateRenderTarget(UINT Width,UINT Height,D3DFORMAT Format,D3DMULTISAMPLE_TYPE MultiSample,DWORD MultisampleQuality,BOOL Lockable,IDirect3DSurface9** ppSurface,HANDLE* pSharedHandle) override { return stubCalled("CreateRenderTarget"); }
    HRESULT STDMETHODCALLTYPE CreateDepthStencilSurface(UINT Width,UINT Height,D3DFORMAT Format,D3DMULTISAMPLE_TYPE MultiSample,DWORD MultisampleQuality,BOOL Discard,IDirect3DSurface9** ppSurface,HANDLE* pSharedHandle) override { return stubCalled("CreateDepthStencilSurface"); }
    HRESULT STDMETHODCALLTYPE UpdateSurface(IDirect3DSurface9* pSourceSurface,const RECT* pSourceRect,IDirect3DSurface9* pDestinationSurface,const POINT* pDestPoint) override { return stubCalled("UpdateSurface"); }
    HRESULT STDMETHODCALLTYPE UpdateTexture(IDirect3DBaseTexture9* pSourceTexture,IDirect3DBaseTexture9* pDestinationTexture) override { return stubCalled("UpdateTexture"); }
    HRESULT STDMETHODCALLTYPE GetRenderTargetData(IDirect3DSurface9* pRenderTarget,IDirect3DSurface9* pDestSurface) override { return stubCalled("GetRenderTargetData"); }
    HRESULT STDMETHODCALLTYPE GetFrontBufferData(UINT iSwapChain,IDirect3DSurface9* pDestSurface) override { return stubCalled("GetFrontBufferData"); }
    HRESULT STDMETHODCALLTYPE StretchRect(IDirect3DSurface9* pSourceSurface,const RECT* pSourceRect,IDirect3DSurface9* pDestSurface,const RECT* pDestRect,D3DTEXTUREFILTERTYPE Filter) override { return stubCalled("StretchRect"); }
    HRESULT STDMETHODCALLTYPE ColorFill(IDirect3DSurface9* pSurface,const RECT* pRect,D3DCOLOR color) override { return stubCalled("ColorFill"); }
    HRESULT STDMETHODCALLTYPE CreateOffscreenPlainSurface(UINT Width,UINT Height,D3DFORMAT Format,D3DPOOL Pool,IDirect3DSurface9** ppSurface,HANDLE* pSharedHandle) override { return stubCalled("CreateOffscreenPlainSurface"); }
    HRESULT STDMETHODCALLTYPE SetRenderTarget(DWORD RenderTargetIndex,IDirect3DSurface9* pRenderTarget) override { return stubCalled("SetRenderTarget"); }
    HRESULT STDMETHODCALLTYPE GetRenderTarget(DWORD RenderTargetIndex,IDirect3DSurface9** ppRenderTarget) override { return stubCalled("GetRenderTarget"); }
    HRESULT STDMETHODCALLTYPE SetDepthStencilSurface(IDirect3DSurface9* pNewZStencil) override { return stubCalled("SetDepthStencilSurface"); }
    HRESULT STDMETHODCALLTYPE GetDepthStencilSurface(IDirect3DSurface9** ppZStencilSurface) override { return stubCalled("GetDepthStencilSurface"); }
    HRESULT STDMETHODCALLTYPE BeginScene() override { return stubCalled("BeginScene"); }
    HRESULT STDMETHODCALLTYPE EndScene() override { return stubCalled("EndScene"); }
    HRESULT STDMETHODCALLTYPE Clear(DWORD Count,const D3DRECT* pRects,DWORD Flags,D3DCOLOR Color,float Z,DWORD Stencil) override { return stubCalled("Clear"); }
    HRESULT STDMETHODCALLTYPE SetTransform(D3DTRANSFORMSTATETYPE State,const D3DMATRIX* pMatrix) override { return stubCalled("SetTransform"); }
    HRESULT STDMETHODCALLTYPE GetTransform(D3DTRANSFORMSTATETYPE State,D3DMATRIX* pMatrix) override { return stubCalled("GetTransform"); }
    HRESULT STDMETHODCALLTYPE MultiplyTransform(D3DTRANSFORMSTATETYPE,const D3DMATRIX*) override { return stubCalled("MultiplyTransform"); }
    HRESULT STDMETHODCALLTYPE SetViewport(const D3DVIEWPORT9* pViewport) override { return stubCalled("SetViewport"); }
    HRESULT STDMETHODCALLTYPE GetViewport(D3DVIEWPORT9* pViewport) override { return stubCalled("GetViewport"); }
    HRESULT STDMETHODCALLTYPE SetMaterial(const D3DMATERIAL9* pMaterial) override { return stubCalled("SetMaterial"); }
    HRESULT STDMETHODCALLTYPE GetMaterial(D3DMATERIAL9* pMaterial) override { return stubCalled("GetMaterial"); }
    HRESULT STDMETHODCALLTYPE SetLight(DWORD Index,const D3DLIGHT9*) override { return stubCalled("SetLight"); }
    HRESULT STDMETHODCALLTYPE GetLight(DWORD Index,D3DLIGHT9*) override { return stubCalled("GetLight"); }
    HRESULT STDMETHODCALLTYPE LightEnable(DWORD Index,BOOL Enable) override { return stubCalled("LightEnable"); }
    HRESULT STDMETHODCALLTYPE GetLightEnable(DWORD Index,BOOL* pEnable) override { return stubCalled("GetLightEnable"); }
    HRESULT STDMETHODCALLTYPE SetClipPlane(DWORD Index,const float* pPlane) override { return stubCalled("SetClipPlane"); }
    HRESULT STDMETHODCALLTYPE GetClipPlane(DWORD Index,float* pPlane) override { return stubCalled("GetClipPlane"); }
    HRESULT STDMETHODCALLTYPE SetRenderState(D3DRENDERSTATETYPE State,DWORD Value) override { return stubCalled("SetRenderState"); }
    HRESULT STDMETHODCALLTYPE GetRenderState(D3DRENDERSTATETYPE State,DWORD* pValue) override { return stubCalled("GetRenderState"); }
    HRESULT STDMETHODCALLTYPE CreateStateBlock(D3DSTATEBLOCKTYPE Type,IDirect3DStateBlock9** ppSB) override { return stubCalled("CreateStateBlock"); }
    HRESULT STDMETHODCALLTYPE BeginStateBlock() override { return stubCalled("BeginStateBlock"); }
    HRESULT STDMETHODCALLTYPE EndStateBlock(IDirect3DStateBlock9** ppSB) override { return stubCalled("EndStateBlock"); }
    HRESULT STDMETHODCALLTYPE SetClipStatus(const D3DCLIPSTATUS9* pClipStatus) override { return stubCalled("SetClipStatus"); }
    HRESULT STDMETHODCALLTYPE GetClipStatus(D3DCLIPSTATUS9* pClipStatus) override { return stubCalled("GetClipStatus"); }
    HRESULT STDMETHODCALLTYPE GetTexture(DWORD Stage,IDirect3DBaseTexture9** ppTexture) override { return stubCalled("GetTexture"); }
    HRESULT STDMETHODCALLTYPE SetTexture(DWORD Stage,IDirect3DBaseTexture9* pTexture) override { return stubCalled("SetTexture"); }
    HRESULT STDMETHODCALLTYPE GetTextureStageState(DWORD Stage,D3DTEXTURESTAGESTATETYPE Type,DWORD* pValue) override { return stubCalled("GetTextureStageState"); }
    HRESULT STDMETHODCALLTYPE SetTextureStageState(DWORD Stage,D3DTEXTURESTAGESTATETYPE Type,DWORD Value) override { return stubCalled("SetTextureStageState"); }
    HRESULT STDMETHODCALLTYPE GetSamplerState(DWORD Sampler,D3DSAMPLERSTATETYPE Type,DWORD* pValue) override { return stubCalled("GetSamplerState"); }
    HRESULT STDMETHODCALLTYPE SetSamplerState(DWORD Sampler,D3DSAMPLERSTATETYPE Type,DWORD Value) override { return stubCalled("SetSamplerState"); }
    HRESULT STDMETHODCALLTYPE ValidateDevice(DWORD* pNumPasses) override { return stubCalled("ValidateDevice"); }
    HRESULT STDMETHODCALLTYPE SetPaletteEntries(UINT PaletteNumber,const PALETTEENTRY* pEntries) override { return stubCalled("SetPaletteEntries"); }
    HRESULT STDMETHODCALLTYPE GetPaletteEntries(UINT PaletteNumber,PALETTEENTRY* pEntries) override { return stubCalled("GetPaletteEntries"); }
    HRESULT STDMETHODCALLTYPE SetCurrentTexturePalette(UINT PaletteNumber) override { return stubCalled("SetCurrentTexturePalette"); }
    HRESULT STDMETHODCALLTYPE GetCurrentTexturePalette(UINT *PaletteNumber) override { return stubCalled("GetCurrentTexturePalette"); }
    HRESULT STDMETHODCALLTYPE SetScissorRect(const RECT* pRect) override { return stubCalled("SetScissorRect"); }
    HRESULT STDMETHODCALLTYPE GetScissorRect(RECT* pRect) override { return stubCalled("GetScissorRect"); }
    HRESULT STDMETHODCALLTYPE SetSoftwareVertexProcessing(BOOL bSoftware) override { return stubCalled("SetSoftwareVertexProcessing"); }
    BOOL STDMETHODCALLTYPE GetSoftwareVertexProcessing() override { stubCalled("GetSoftwareVertexProcessing"); return {}; }
    HRESULT STDMETHODCALLTYPE SetNPatchMode(float nSegments) override { return stubCalled("SetNPatchMode"); }
    float STDMETHODCALLTYPE GetNPatchMode() override { stubCalled("GetNPatchMode"); return {}; }
    HRESULT STDMETHODCALLTYPE DrawPrimitive(D3DPRIMITIVETYPE PrimitiveType,UINT StartVertex,UINT PrimitiveCount) override { return stubCalled("DrawPrimitive"); }
    HRESULT STDMETHODCALLTYPE DrawIndexedPrimitive(D3DPRIMITIVETYPE,INT BaseVertexIndex,UINT MinVertexIndex,UINT NumVertices,UINT startIndex,UINT primCount) override { return stubCalled("DrawIndexedPrimitive"); }
    HRESULT STDMETHODCALLTYPE DrawPrimitiveUP(D3DPRIMITIVETYPE PrimitiveType,UINT PrimitiveCount,const void* pVertexStreamZeroData,UINT VertexStreamZeroStride) override { return stubCalled("DrawPrimitiveUP"); }
    HRESULT STDMETHODCALLTYPE DrawIndexedPrimitiveUP(D3DPRIMITIVETYPE PrimitiveType,UINT MinVertexIndex,UINT NumVertices,UINT PrimitiveCount,const void* pIndexData,D3DFORMAT IndexDataFormat,const void* pVertexStreamZeroData,UINT VertexStreamZeroStride) override { return stubCalled("DrawIndexedPrimitiveUP"); }
    HRESULT STDMETHODCALLTYPE ProcessVertices(UINT SrcStartIndex,UINT DestIndex,UINT VertexCount,IDirect3DVertexBuffer9* pDestBuffer,IDirect3DVertexDeclaration9* pVertexDecl,DWORD Flags) override { return stubCalled("ProcessVertices"); }
    HRESULT STDMETHODCALLTYPE CreateVertexDeclaration(const D3DVERTEXELEMENT9* pVertexElements,IDirect3DVertexDeclaration9** ppDecl) override { return stubCalled("CreateVertexDeclaration"); }
    HRESULT STDMETHODCALLTYPE SetVertexDeclaration(IDirect3DVertexDeclaration9* pDecl) override { return stubCalled("SetVertexDeclaration"); }
    HRESULT STDMETHODCALLTYPE GetVertexDeclaration(IDirect3DVertexDeclaration9** ppDecl) override { return stubCalled("GetVertexDeclaration"); }
    HRESULT STDMETHODCALLTYPE SetFVF(DWORD FVF) override { return stubCalled("SetFVF"); }
    HRESULT STDMETHODCALLTYPE GetFVF(DWORD* pFVF) override { return stubCalled("GetFVF"); }
    HRESULT STDMETHODCALLTYPE CreateVertexShader(const DWORD* pFunction,IDirect3DVertexShader9** ppShader) override { return stubCalled("CreateVertexShader"); }
    HRESULT STDMETHODCALLTYPE SetVertexShader(IDirect3DVertexShader9* pShader) override { return stubCalled("SetVertexShader"); }
    HRESULT STDMETHODCALLTYPE GetVertexShader(IDirect3DVertexShader9** ppShader) override { return stubCalled("GetVertexShader"); }
    HRESULT STDMETHODCALLTYPE SetVertexShaderConstantF(UINT StartRegister,const float* pConstantData,UINT Vector4fCount) override { return stubCalled("SetVertexShaderConstantF"); }
    HRESULT STDMETHODCALLTYPE GetVertexShaderConstantF(UINT StartRegister,float* pConstantData,UINT Vector4fCount) override { return stubCalled("GetVertexShaderConstantF"); }
    HRESULT STDMETHODCALLTYPE SetVertexShaderConstantI(UINT StartRegister,const int* pConstantData,UINT Vector4iCount) override { return stubCalled("SetVertexShaderConstantI"); }
    HRESULT STDMETHODCALLTYPE GetVertexShaderConstantI(UINT StartRegister,int* pConstantData,UINT Vector4iCount) override { return stubCalled("GetVertexShaderConstantI"); }
    HRESULT STDMETHODCALLTYPE SetVertexShaderConstantB(UINT StartRegister,const BOOL* pConstantData,UINT  BoolCount) override { return stubCalled("SetVertexShaderConstantB"); }
    HRESULT STDMETHODCALLTYPE GetVertexShaderConstantB(UINT StartRegister,BOOL* pConstantData,UINT BoolCount) override { return stubCalled("GetVertexShaderConstantB"); }
    HRESULT STDMETHODCALLTYPE SetStreamSource(UINT StreamNumber,IDirect3DVertexBuffer9* pStreamData,UINT OffsetInBytes,UINT Stride) override { return stubCalled("SetStreamSource"); }
    HRESULT STDMETHODCALLTYPE GetStreamSource(UINT StreamNumber,IDirect3DVertexBuffer9** ppStreamData,UINT* pOffsetInBytes,UINT* pStride) override { return stubCalled("GetStreamSource"); }
    HRESULT STDMETHODCALLTYPE SetStreamSourceFreq(UINT StreamNumber,UINT Setting) override { return stubCalled("SetStreamSourceFreq"); }
    HRESULT STDMETHODCALLTYPE GetStreamSourceFreq(UINT StreamNumber,UINT* pSetting) override { return stubCalled("GetStreamSourceFreq"); }
    HRESULT STDMETHODCALLTYPE SetIndices(IDirect3DIndexBuffer9* pIndexData) override { return stubCalled("SetIndices"); }
    HRESULT STDMETHODCALLTYPE GetIndices(IDirect3DIndexBuffer9** ppIndexData) override { return stubCalled("GetIndices"); }
    HRESULT STDMETHODCALLTYPE CreatePixelShader(const DWORD* pFunction,IDirect3DPixelShader9** ppShader) override { return stubCalled("CreatePixelShader"); }
    HRESULT STDMETHODCALLTYPE SetPixelShader(IDirect3DPixelShader9* pShader) override { return stubCalled("SetPixelShader"); }
    HRESULT STDMETHODCALLTYPE GetPixelShader(IDirect3DPixelShader9** ppShader) override { return stubCalled("GetPixelShader"); }
    HRESULT STDMETHODCALLTYPE SetPixelShaderConstantF(UINT StartRegister,const float* pConstantData,UINT Vector4fCount) override { return stubCalled("SetPixelShaderConstantF"); }
    HRESULT STDMETHODCALLTYPE GetPixelShaderConstantF(UINT StartRegister,float* pConstantData,UINT Vector4fCount) override { return stubCalled("GetPixelShaderConstantF"); }
    HRESULT STDMETHODCALLTYPE SetPixelShaderConstantI(UINT StartRegister,const int* pConstantData,UINT Vector4iCount) override { return stubCalled("SetPixelShaderConstantI"); }
    HRESULT STDMETHODCALLTYPE GetPixelShaderConstantI(UINT StartRegister,int* pConstantData,UINT Vector4iCount) override { return stubCalled("GetPixelShaderConstantI"); }
    HRESULT STDMETHODCALLTYPE SetPixelShaderConstantB(UINT StartRegister,const BOOL* pConstantData,UINT  BoolCount) override { return stubCalled("SetPixelShaderConstantB"); }
    HRESULT STDMETHODCALLTYPE GetPixelShaderConstantB(UINT StartRegister,BOOL* pConstantData,UINT BoolCount) override { return stubCalled("GetPixelShaderConstantB"); }
    HRESULT STDMETHODCALLTYPE DrawRectPatch(UINT Handle,const float* pNumSegs,const D3DRECTPATCH_INFO* pRectPatchInfo) override { return stubCalled("DrawRectPatch"); }
    HRESULT STDMETHODCALLTYPE DrawTriPatch(UINT Handle,const float* pNumSegs,const D3DTRIPATCH_INFO* pTriPatchInfo) override { return stubCalled("DrawTriPatch"); }
    HRESULT STDMETHODCALLTYPE DeletePatch(UINT Handle) override { return stubCalled("DeletePatch"); }
    HRESULT STDMETHODCALLTYPE CreateQuery(D3DQUERYTYPE Type,IDirect3DQuery9** ppQuery) override { return stubCalled("CreateQuery"); }
};

struct StubDirect3DTexture9 : IDirect3DTexture9 {
    LONG m_refs = 1;
    virtual ~StubDirect3DTexture9() = default;
    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, void** ppvObj) override { if (ppvObj) *ppvObj = nullptr; return E_NOINTERFACE; }
    ULONG STDMETHODCALLTYPE AddRef() override { return static_cast<ULONG>(InterlockedIncrement(&m_refs)); }
    ULONG STDMETHODCALLTYPE Release() override { const LONG refs = InterlockedDecrement(&m_refs); if (refs == 0) delete this; return static_cast<ULONG>(refs); }
    HRESULT STDMETHODCALLTYPE GetDevice(IDirect3DDevice9** ppDevice) override { return stubCalled("GetDevice"); }
    HRESULT STDMETHODCALLTYPE SetPrivateData(REFGUID refguid,const void* pData,DWORD SizeOfData,DWORD Flags) override { return stubCalled("SetPrivateData"); }
    HRESULT STDMETHODCALLTYPE GetPrivateData(REFGUID refguid,void* pData,DWORD* pSizeOfData) override { return stubCalled("GetPrivateData"); }
    HRESULT STDMETHODCALLTYPE FreePrivateData(REFGUID refguid) override { return stubCalled("FreePrivateData"); }
    DWORD STDMETHODCALLTYPE SetPriority(DWORD PriorityNew) override { stubCalled("SetPriority"); return {}; }
    DWORD STDMETHODCALLTYPE GetPriority() override { stubCalled("GetPriority"); return {}; }
    void STDMETHODCALLTYPE PreLoad() override { stubCalled("PreLoad"); }
    D3DRESOURCETYPE STDMETHODCALLTYPE GetType() override { stubCalled("GetType"); return {}; }
    DWORD STDMETHODCALLTYPE SetLOD(DWORD LODNew) override { stubCalled("SetLOD"); return {}; }
    DWORD STDMETHODCALLTYPE GetLOD() override { stubCalled("GetLOD"); return {}; }
    DWORD STDMETHODCALLTYPE GetLevelCount() override { stubCalled("GetLevelCount"); return {}; }
    HRESULT STDMETHODCALLTYPE SetAutoGenFilterType(D3DTEXTUREFILTERTYPE FilterType) override { return stubCalled("SetAutoGenFilterType"); }
    D3DTEXTUREFILTERTYPE STDMETHODCALLTYPE GetAutoGenFilterType() override { stubCalled("GetAutoGenFilterType"); return {}; }
    void STDMETHODCALLTYPE GenerateMipSubLevels() override { stubCalled("GenerateMipSubLevels"); }
    HRESULT STDMETHODCALLTYPE GetLevelDesc(UINT Level,D3DSURFACE_DESC *pDesc) override { return stubCalled("GetLevelDesc"); }
    HRESULT STDMETHODCALLTYPE GetSurfaceLevel(UINT Level,IDirect3DSurface9** ppSurfaceLevel) override { return stubCalled("GetSurfaceLevel"); }
    HRESULT STDMETHODCALLTYPE LockRect(UINT Level,D3DLOCKED_RECT* pLockedRect,const RECT* pRect,DWORD Flags) override { return stubCalled("LockRect"); }
    HRESULT STDMETHODCALLTYPE UnlockRect(UINT Level) override { return stubCalled("UnlockRect"); }
    HRESULT STDMETHODCALLTYPE AddDirtyRect(const RECT* pDirtyRect) override { return stubCalled("AddDirtyRect"); }
};

struct StubDirect3DCubeTexture9 : IDirect3DCubeTexture9 {
    LONG m_refs = 1;
    virtual ~StubDirect3DCubeTexture9() = default;
    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, void** ppvObj) override { if (ppvObj) *ppvObj = nullptr; return E_NOINTERFACE; }
    ULONG STDMETHODCALLTYPE AddRef() override { return static_cast<ULONG>(InterlockedIncrement(&m_refs)); }
    ULONG STDMETHODCALLTYPE Release() override { const LONG refs = InterlockedDecrement(&m_refs); if (refs == 0) delete this; return static_cast<ULONG>(refs); }
    HRESULT STDMETHODCALLTYPE GetDevice(IDirect3DDevice9** ppDevice) override { return stubCalled("GetDevice"); }
    HRESULT STDMETHODCALLTYPE SetPrivateData(REFGUID refguid,const void* pData,DWORD SizeOfData,DWORD Flags) override { return stubCalled("SetPrivateData"); }
    HRESULT STDMETHODCALLTYPE GetPrivateData(REFGUID refguid,void* pData,DWORD* pSizeOfData) override { return stubCalled("GetPrivateData"); }
    HRESULT STDMETHODCALLTYPE FreePrivateData(REFGUID refguid) override { return stubCalled("FreePrivateData"); }
    DWORD STDMETHODCALLTYPE SetPriority(DWORD PriorityNew) override { stubCalled("SetPriority"); return {}; }
    DWORD STDMETHODCALLTYPE GetPriority() override { stubCalled("GetPriority"); return {}; }
    void STDMETHODCALLTYPE PreLoad() override { stubCalled("PreLoad"); }
    D3DRESOURCETYPE STDMETHODCALLTYPE GetType() override { stubCalled("GetType"); return {}; }
    DWORD STDMETHODCALLTYPE SetLOD(DWORD LODNew) override { stubCalled("SetLOD"); return {}; }
    DWORD STDMETHODCALLTYPE GetLOD() override { stubCalled("GetLOD"); return {}; }
    DWORD STDMETHODCALLTYPE GetLevelCount() override { stubCalled("GetLevelCount"); return {}; }
    HRESULT STDMETHODCALLTYPE SetAutoGenFilterType(D3DTEXTUREFILTERTYPE FilterType) override { return stubCalled("SetAutoGenFilterType"); }
    D3DTEXTUREFILTERTYPE STDMETHODCALLTYPE GetAutoGenFilterType() override { stubCalled("GetAutoGenFilterType"); return {}; }
    void STDMETHODCALLTYPE GenerateMipSubLevels() override { stubCalled("GenerateMipSubLevels"); }
    HRESULT STDMETHODCALLTYPE GetLevelDesc(UINT Level,D3DSURFACE_DESC *pDesc) override { return stubCalled("GetLevelDesc"); }
    HRESULT STDMETHODCALLTYPE GetCubeMapSurface(D3DCUBEMAP_FACES FaceType,UINT Level,IDirect3DSurface9** ppCubeMapSurface) override { return stubCalled("GetCubeMapSurface"); }
    HRESULT STDMETHODCALLTYPE LockRect(D3DCUBEMAP_FACES FaceType,UINT Level,D3DLOCKED_RECT* pLockedRect,const RECT* pRect,DWORD Flags) override { return stubCalled("LockRect"); }
    HRESULT STDMETHODCALLTYPE UnlockRect(D3DCUBEMAP_FACES FaceType,UINT Level) override { return stubCalled("UnlockRect"); }
    HRESULT STDMETHODCALLTYPE AddDirtyRect(D3DCUBEMAP_FACES FaceType,const RECT* pDirtyRect) override { return stubCalled("AddDirtyRect"); }
};

struct StubDirect3DSurface9 : IDirect3DSurface9 {
    LONG m_refs = 1;
    virtual ~StubDirect3DSurface9() = default;
    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, void** ppvObj) override { if (ppvObj) *ppvObj = nullptr; return E_NOINTERFACE; }
    ULONG STDMETHODCALLTYPE AddRef() override { return static_cast<ULONG>(InterlockedIncrement(&m_refs)); }
    ULONG STDMETHODCALLTYPE Release() override { const LONG refs = InterlockedDecrement(&m_refs); if (refs == 0) delete this; return static_cast<ULONG>(refs); }
    HRESULT STDMETHODCALLTYPE GetDevice(IDirect3DDevice9** ppDevice) override { return stubCalled("GetDevice"); }
    HRESULT STDMETHODCALLTYPE SetPrivateData(REFGUID refguid,const void* pData,DWORD SizeOfData,DWORD Flags) override { return stubCalled("SetPrivateData"); }
    HRESULT STDMETHODCALLTYPE GetPrivateData(REFGUID refguid,void* pData,DWORD* pSizeOfData) override { return stubCalled("GetPrivateData"); }
    HRESULT STDMETHODCALLTYPE FreePrivateData(REFGUID refguid) override { return stubCalled("FreePrivateData"); }
    DWORD STDMETHODCALLTYPE SetPriority(DWORD PriorityNew) override { stubCalled("SetPriority"); return {}; }
    DWORD STDMETHODCALLTYPE GetPriority() override { stubCalled("GetPriority"); return {}; }
    void STDMETHODCALLTYPE PreLoad() override { stubCalled("PreLoad"); }
    D3DRESOURCETYPE STDMETHODCALLTYPE GetType() override { stubCalled("GetType"); return {}; }
    HRESULT STDMETHODCALLTYPE GetContainer(REFIID riid,void** ppContainer) override { return stubCalled("GetContainer"); }
    HRESULT STDMETHODCALLTYPE GetDesc(D3DSURFACE_DESC *pDesc) override { return stubCalled("GetDesc"); }
    HRESULT STDMETHODCALLTYPE LockRect(D3DLOCKED_RECT* pLockedRect,const RECT* pRect,DWORD Flags) override { return stubCalled("LockRect"); }
    HRESULT STDMETHODCALLTYPE UnlockRect() override { return stubCalled("UnlockRect"); }
    HRESULT STDMETHODCALLTYPE GetDC(HDC *phdc) override { return stubCalled("GetDC"); }
    HRESULT STDMETHODCALLTYPE ReleaseDC(HDC hdc) override { return stubCalled("ReleaseDC"); }
};

struct StubDirect3DVertexShader9 : IDirect3DVertexShader9 {
    LONG m_refs = 1;
    virtual ~StubDirect3DVertexShader9() = default;
    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, void** ppvObj) override { if (ppvObj) *ppvObj = nullptr; return E_NOINTERFACE; }
    ULONG STDMETHODCALLTYPE AddRef() override { return static_cast<ULONG>(InterlockedIncrement(&m_refs)); }
    ULONG STDMETHODCALLTYPE Release() override { const LONG refs = InterlockedDecrement(&m_refs); if (refs == 0) delete this; return static_cast<ULONG>(refs); }
    HRESULT STDMETHODCALLTYPE GetDevice(IDirect3DDevice9** ppDevice) override { return stubCalled("GetDevice"); }
    HRESULT STDMETHODCALLTYPE GetFunction(void*,UINT* pSizeOfData) override { return stubCalled("GetFunction"); }
};

struct StubDirect3DPixelShader9 : IDirect3DPixelShader9 {
    LONG m_refs = 1;
    virtual ~StubDirect3DPixelShader9() = default;
    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, void** ppvObj) override { if (ppvObj) *ppvObj = nullptr; return E_NOINTERFACE; }
    ULONG STDMETHODCALLTYPE AddRef() override { return static_cast<ULONG>(InterlockedIncrement(&m_refs)); }
    ULONG STDMETHODCALLTYPE Release() override { const LONG refs = InterlockedDecrement(&m_refs); if (refs == 0) delete this; return static_cast<ULONG>(refs); }
    HRESULT STDMETHODCALLTYPE GetDevice(IDirect3DDevice9** ppDevice) override { return stubCalled("GetDevice"); }
    HRESULT STDMETHODCALLTYPE GetFunction(void*,UINT* pSizeOfData) override { return stubCalled("GetFunction"); }
};

struct StubDirect3DVertexDeclaration9 : IDirect3DVertexDeclaration9 {
    LONG m_refs = 1;
    virtual ~StubDirect3DVertexDeclaration9() = default;
    HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, void** ppvObj) override { if (ppvObj) *ppvObj = nullptr; return E_NOINTERFACE; }
    ULONG STDMETHODCALLTYPE AddRef() override { return static_cast<ULONG>(InterlockedIncrement(&m_refs)); }
    ULONG STDMETHODCALLTYPE Release() override { const LONG refs = InterlockedDecrement(&m_refs); if (refs == 0) delete this; return static_cast<ULONG>(refs); }
    HRESULT STDMETHODCALLTYPE GetDevice(IDirect3DDevice9** ppDevice) override { return stubCalled("GetDevice"); }
    HRESULT STDMETHODCALLTYPE GetDeclaration(D3DVERTEXELEMENT9* pElement,UINT* pNumElements) override { return stubCalled("GetDeclaration"); }
};

}  // namespace cw::d3d
