"""Generates native_port/runtime/d3d/D3D9Stubs.h: default implementations of the Direct3D 9 interfaces that the
Direct3D 11 renderer (Device11.cpp) implements in part. Every method fails (E_NOTIMPL, logged once) or does nothing
unless a derived class overrides it; IUnknown is a plain reference count.

Usage: python tools/gen_d3d9_stubs.py [path to the Windows SDK's shared/d3d9.h]
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INTERFACES = ["IDirect3DDevice9", "IDirect3DTexture9", "IDirect3DCubeTexture9", "IDirect3DSurface9",
              "IDirect3DVertexShader9", "IDirect3DPixelShader9", "IDirect3DVertexDeclaration9"]


def find_header():
    if len(sys.argv) > 1:
        return Path(sys.argv[1])
    kits = Path(r"C:\Program Files (x86)\Windows Kits\10\Include")
    return sorted(kits.glob("*/shared/d3d9.h"))[-1]


def methods(text, interface):
    match = re.search(r"DECLARE_INTERFACE_\(%s,\s*\w+\)\s*\{(.*?)\n\};" % interface, text, re.S)
    assert match, interface
    for line in match.group(1).splitlines():
        found = re.match(r"\s*STDMETHOD(?:_\(\s*([^,]+?)\s*,\s*(\w+)\)|\((\w+)\))\(THIS_?\s*(.*?)\)\s*PURE;", line)
        if not found:
            continue
        result = found.group(1) or "HRESULT"
        name = found.group(2) or found.group(3)
        yield result, name, found.group(4).strip()


def body(result, name):
    if name == "QueryInterface":
        return "{ if (ppvObj) *ppvObj = nullptr; return E_NOINTERFACE; }"
    if name == "AddRef":
        return "{ return static_cast<ULONG>(InterlockedIncrement(&m_refs)); }"
    if name == "Release":
        return "{ const LONG refs = InterlockedDecrement(&m_refs); if (refs == 0) delete this; return static_cast<ULONG>(refs); }"
    if result == "HRESULT":
        return '{ return stubCalled("%s"); }' % name
    if result == "void":
        return '{ stubCalled("%s"); }' % name
    return '{ stubCalled("%s"); return {}; }' % name


def main():
    text = find_header().read_text(encoding="latin-1")
    out = ["// Generated by tools/gen_d3d9_stubs.py from the Windows SDK's d3d9.h; do not edit.",
           "#pragma once", "", "#include <d3d9.h>", "", "namespace cw::d3d {", "",
           "// Logs the first call of each unimplemented method; returns E_NOTIMPL.",
           "HRESULT stubCalled(const char* method);", ""]
    for interface in INTERFACES:
        out.append(f"struct Stub{interface[1:]} : {interface} {{")
        out.append("    LONG m_refs = 1;")
        out.append(f"    virtual ~Stub{interface[1:]}() = default;")
        for result, name, arguments in methods(text, interface):
            arguments = arguments.replace("CONST ", "const ")
            out.append(f"    {result} STDMETHODCALLTYPE {name}({arguments}) override {body(result, name)}")
        out.append("};")
        out.append("")
    out.append("}  // namespace cw::d3d")
    target = ROOT / "native_port" / "runtime" / "d3d" / "D3D9Stubs.h"
    target.write_text("\n".join(out) + "\n")
    print(f"wrote {target}")


if __name__ == "__main__":
    main()
