"""Generates native_port/runtime/game/GameSymbols.h from the symbol database.

Usage: python tools/re/gen_header.py

Inputs:
  symbols/manual.csv          curated names (kind,address,name,type,comment); a type makes a typed accessor.
                              Function types are written like "void __cdecl(float dt)" with parameters separated
                              by ';' instead of ','.
  symbols/auto/functions.csv  generated function names (address constants only)
  symbols/auto/globals.csv    generated global names (address constants only)
  symbols/auto/factories.csv  class hierarchy (constructor -> vtable chain)
  symbols/auto/odf_fields.csv ODF key -> class field offset

Manual names win over generated names at the same address.
"""

import csv
import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SYMBOLS = ROOT / "symbols"
OUT = ROOT / "native_port" / "runtime" / "game" / "GameSymbols.h"

FORMAT_TYPES = {"%f": "float", "%d": "std::int32_t", "%i": "std::int32_t", "%u": "std::uint32_t", "%x": "std::uint32_t", "%c": "char"}


def read(path):
    with open(path, newline="") as handle:
        return list(csv.DictReader(handle))


def identifier(text):
    text = re.sub(r"::", "_", text)
    text = re.sub(r"\W", "_", text)
    return text if not text[0].isdigit() else "_" + text


def function_pointer(name, signature, address):
    match = re.fullmatch(r"\s*(.+?)\s+(__cdecl|__stdcall|__fastcall|__thiscall)\s*\((.*)\)\s*", signature)
    if not match:
        raise ValueError(f"{name}: cannot parse signature '{signature}'")
    result, convention, parameters = match.groups()
    parameters = ", ".join(p.strip() for p in parameters.split(";") if p.strip())
    if convention == "__thiscall":
        # A free function pointer cannot be __thiscall; __fastcall with an unused edx argument matches the ABI.
        parts = [p.strip() for p in parameters.split(",") if p.strip()]
        parameters = ", ".join([parts[0], "void* /*edx*/"] + parts[1:]) if parts else "void*, void*"
        convention = "__fastcall"
    return f"inline const auto {name} = reinterpret_cast<{result}({convention}*)({parameters})>(0x{address:08X});"


def field_type(fmt):
    tokens = re.findall(r"%\[?[^\s\"]*", fmt)
    if not tokens:
        return None, 0
    first = tokens[0]
    if first.startswith("%["):
        return "char", 0  # string: buffer size unknown
    base = FORMAT_TYPES.get(first[:2])
    if base is None or any(token[:2] != first[:2] for token in tokens):
        return None, 0
    return base, len(tokens)


def main():
    manual = read(SYMBOLS / "manual.csv")
    manual_addresses = {int(row["address"], 16) for row in manual}
    lines = [
        "// Generated by tools/re/gen_header.py from symbols/*.csv. Do not edit; edit symbols/manual.csv instead.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace cw::game {",
        "",
        "// ---- Curated symbols (symbols/manual.csv)",
    ]
    for row in manual:
        address = int(row["address"], 16)
        name = identifier(row["name"])
        comment = f"  // {row['comment']}" if row["comment"] else ""
        if row["kind"] == "function" and row["type"]:
            lines.append(function_pointer(name, row["type"], address) + comment)
        elif row["kind"] == "global" and row["type"]:
            lines.append(f"inline {row['type']}* const {name} = reinterpret_cast<{row['type']}*>(0x{address:08X});{comment}")
        else:
            lines.append(f"constexpr std::uint32_t {name} = 0x{address:08X};{comment}")

    lines += ["", "// ---- Generated addresses (symbols/auto)", "namespace addr {"]
    seen = set()
    for file in ("functions.csv", "globals.csv"):
        for row in read(SYMBOLS / "auto" / file):
            address = int(row["address"], 16)
            name = identifier(row["name"])
            if address in manual_addresses or name in seen:
                continue
            seen.add(name)
            lines.append(f"constexpr std::uint32_t {name} = 0x{address:08X};")
    lines.append("} // namespace addr")

    # Class definitions (ODF-backed prototypes): accessors for every field the ODF loaders fill.
    parent_of = {}
    vtable_of = {}
    for row in read(SYMBOLS / "auto" / "factories.csv"):
        if not row["class"] or row["class"].startswith("Factory_"):
            continue
        chain = [link.split(":") for link in row["constructor_vtable_chain"].split()]
        vtable_of.setdefault(row["class"], int(chain[0][1], 16))
    vtable_class = {vtable: name for name, vtable in vtable_of.items()}
    for row in read(SYMBOLS / "auto" / "factories.csv"):
        chain = [int(link.split(":")[1], 16) for link in row["constructor_vtable_chain"].split()]
        for child, parent in zip(chain, chain[1:]):
            if child in vtable_class and parent in vtable_class:
                parent_of.setdefault(vtable_class[child], vtable_class[parent])
    fields = defaultdict(dict)
    for row in read(SYMBOLS / "auto" / "odf_fields.csv"):
        if not row["class"] or not row["offset"]:
            continue
        kind, count = field_type(row["format"])
        if kind is None:
            continue
        name = identifier(row["key"])
        fields[row["class"]].setdefault(name, (int(row["offset"], 16), kind, count, row["section"]))

    lines += [
        "",
        "// ---- ODF-backed class definitions (prototype objects built from .odf files)",
        "// Field offsets come from the ODF loaders: key -> destination of its sscanf().",
        "struct ClassView {",
        "    void* self;",
        "    template <typename T> T& at(std::uint32_t offset) const { return *reinterpret_cast<T*>(static_cast<std::uint8_t*>(self) + offset); }",
        "};",
    ]
    ordered = []
    def visit(name):
        if name in ordered:
            return
        if name in parent_of:
            visit(parent_of[name])
        ordered.append(name)
    for name in sorted(vtable_of):
        visit(name)
    for name in ordered:
        parent = parent_of.get(name, "ClassView")
        lines.append(f"struct {name} : {parent} {{")
        lines.append(f"    static constexpr std::uint32_t kVtable = 0x{vtable_of[name]:08X};")
        for field, (offset, kind, count, section) in sorted(fields.get(name, {}).items(), key=lambda item: item[1][0]):
            if count > 1:
                lines.append(f"    {kind}* {field}() const {{ return &at<{kind}>(0x{offset:X}); }}  // {section} {count} values")
            elif kind == "char":
                lines.append(f"    char* {field}() const {{ return &at<char>(0x{offset:X}); }}  // {section} string")
            else:
                lines.append(f"    {kind}& {field}() const {{ return at<{kind}>(0x{offset:X}); }}  // {section}")
        lines.append("};")
    lines += ["", "} // namespace cw::game", ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}: {len(lines)} lines")


if __name__ == "__main__":
    main()
